git-svn-id: http://svn.seqan.de/seqan/trunk@2278 e6417c60-b987-48fd-844e-b20f0fcc1017

diff --git a/seqan/projects/library/apps/Makefile b/seqan/projects/library/apps/Makefile
--- a/seqan/projects/library/apps/Makefile
+++ b/seqan/projects/library/apps/Makefile
@@ -1,8 +1,8 @@
-SEQAN = ..
+SEQAN_BASE = ..
 
 # The following line is for the SVN repository
 # You can remove it, if you use the release/snapshot
-CPPFLAGS += -I$(SEQAN)/../../platforms/gcc
+CPPFLAGS += -I$(SEQAN_BASE)/../../platforms/gcc
 
 # Link against runtime library on Linux systems
 OS_NAME=$(shell uname)
@@ -10,13 +10,20 @@ ifeq ($(OS_NAME),Linux)
   LDFLAGS += -lrt
 endif
 
-CPPFLAGS += -I$(SEQAN)
+CPPFLAGS += -I$(SEQAN_BASE)
 CPPFLAGS += -O9
 CPPFLAGS += -pedantic
 CPPFLAGS += -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
 
 TARGETS = razers/razers seqan_tcoffee/seqan_tcoffee
 
-all: $(TARGETS)
+all: check_seqan_base $(TARGETS)
+
+check_seqan_base:
+	@if [ ! -d "$(SEQAN_BASE)/seqan" ]; then \
+		echo "The directory $(SEQAN_BASE)/seqan could not be found!"; \
+		exit 1; \
+	fi
+
 clean:
 	rm -f $(TARGETS)
